[package]
name = "k-means-gpu"
version = "0.1.0"
edition = "2021"
description = "Calculates the k average colors in an image."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
image = "0.24"
wgpu = "0.12"
bytemuck = { version = "1.8", features = ["derive"] }
anyhow = "1.0"
pollster = "0.2"
rand = "0.8"
clap = { version = "3.0", features = ["cargo"] }
